[package]
name = "spritz"
version = "0.1.0"
authors = ["Aaron Goldman <GoldmanAaron@gmail.com>"]
edition = "2018"

[profile.release]
debug = true

[dependencies]
dirs = "2.0"
json = "0.12.4"
users = "0.10.0"
